// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYsfTsZF6QEh2m13FV_V0qlrRmPoX96cs',
    appId: '1:1022871190368:web:74ee3a9ba232353d77bc05',
    messagingSenderId: '1022871190368',
    projectId: 'hider-c122b',
    authDomain: 'hider-c122b.firebaseapp.com',
    storageBucket: 'hider-c122b.appspot.com',
    measurementId: 'G-CMDEFVJ9X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9yrKmOR0PtI4OmN1w4WgWdhE-rKaYOog',
    appId: '1:1022871190368:android:d0354a46215044d277bc05',
    messagingSenderId: '1022871190368',
    projectId: 'hider-c122b',
    storageBucket: 'hider-c122b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHyBLWt7nfevTEM3WN_sMj-1JCNPYWr1A',
    appId: '1:1022871190368:ios:cf2c7fbb14a3193577bc05',
    messagingSenderId: '1022871190368',
    projectId: 'hider-c122b',
    storageBucket: 'hider-c122b.appspot.com',
    iosClientId:
        '1022871190368-sfbqosbd6jfjr9rbtngbjqg4kpf5ikn3.apps.googleusercontent.com',
    iosBundleId: 'com.valentinvignal.hider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHyBLWt7nfevTEM3WN_sMj-1JCNPYWr1A',
    appId: '1:1022871190368:ios:cf2c7fbb14a3193577bc05',
    messagingSenderId: '1022871190368',
    projectId: 'hider-c122b',
    storageBucket: 'hider-c122b.appspot.com',
    iosClientId:
        '1022871190368-sfbqosbd6jfjr9rbtngbjqg4kpf5ikn3.apps.googleusercontent.com',
    iosBundleId: 'com.valentinvignal.hider',
  );
}
